### ISSUE TITLE
Compatibility with Django CMS 3.6

### ISSUE THREAD

**Issue by joeljv91** [divio/djangocms-history#30]
It's compatible with this version?

I installed the latest Django CMS 3.6 version and after execute a migration this error appear on console:

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/www/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/var/www/venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/venv/lib/python3.5/site-packages/djangocms_history/models.py", line 25, in <module>
    from . import action_handlers
  File "/var/www/venv/lib/python3.5/site-packages/djangocms_history/action_handlers.py", line 4, in <module>
    from .helpers import delete_plugins, disable_cms_plugin_signals
  File "/var/www/venv/lib/python3.5/site-packages/djangocms_history/helpers.py", line 11, in <module>
    from cms.signals import (
ImportError: cannot import name 'pre_delete_plugins'

Any ideas?

Thanks

**Comment by joeljv91** [comment]
Ok on Django CMS 3.6 they remove this signals.

https://github.com/divio/django-cms/commit/99880979884de94b1f2784bb830ad5cf6d7bdea7#diff-643105bbf8c6920853343a09e34d38ac

So for the moment it's not compatible. It's a little bit confusing the requirements compatibility on the doc page "Django 3.4+"

**Comment by FinalAngel** [comment]
@joeljv91 the tests for 3.4, 3.5 and 3.6 pass plus we use it on several instances by now. What version where you using?
